- name: Create main directory if not exists for plex
  ansible.builtin.file:
    path: "/data/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "medias"
    - "database"
    - "transcode"

- name: Create media subfolder if not exists for plex
  ansible.builtin.file:
    path: "/data/medias/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "Movies"
    - "TV Shows"

- name: Docker container of Plex MediaServer
  docker_container:
    name: plex_MS
    state: present
    image: "plexinc/pms-docker:{{ plex_version }}"
    network_mode: bridge
    devices:
     - "/dev/dri:/dev/dri" # Diserve for i-GPU use
    env:
      TZ: "{{ timezone }}"
      PLEX_CLAIM: "{{ claim_token }}"
      ADVERTISE_IP: ""
    ports:
      - "32400:32400/tcp"
    hostname: "PlexServer"
    volumes:
      - /data/database:/config
      - /data/transcode:/transcode
      - /data/medias:/data